FROM node:18-alpine

WORKDIR /admin-ui

COPY . .

RUN npm ci
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
ENV NEXT_PUBLIC_PIPEBIRD_BASE_URL ${NEXT_PUBLIC_PIPEBIRD_BASE_URL}
ENV NEXT_PUBLIC_TLS ${NEXT_PUBLIC_TLS:-NO_TLS}
ENV PORT ${PORT:-375}
RUN chmod +x ./start.sh

CMD ["sh", "./start.sh"]